name: staging-ingress-pipeline

on: push

jobs:
  eval:
    name: Evaluate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test ingress config file
      uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
      with: 
       files: kubernetes/ingress/staging/ingress.staging.yml