name: staging-ingress-pipeline

on: push

jobs:
  kubeval:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test ingress config file
      uses: instrumenta/kubeval-action@master
      with: 
       files: kubernetes/ingress/staging/ingress.staging.yml