name: staging-ingress-pipeline

on: push

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - name: kubeconform
      - uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          args: "-summary -output json kubernetes/ingress/staging/ingress.staging.yml"